### PR TITLE
Added function to compare hashes' bits

### PR DESCRIPTION
**Pull request by Effanuel**
An additional function that compares a pair of hashed strings *(differ by 1 character)*.

### Returns:
* Benchmark time;
* Bits per single hash;
* **Average** bit difference out of all hashes;
* **Min** and **max** bit difference between single hashes;

P.S.: fixed small warning of an unused variable

### CODE REVIEW

**Comment by gitguuddd** [comment]
## Found a few issues
1. ```#``` was not removed from bit_collision call in main function - remove before testing.
Screenshot_2
2. Suspicion that the bit_collision function is not universal - my hash generator  produces the following output when tested with bit_collision.
Screenshot_3
- Somehow the bit_collision function manages to find 103% matching bits
- In the PR description it's mentioned that the function returns difference percentages, however the output shows the percentage of matching bits (similarity) - possible output text/code logic mistake
- I don't know if it's intended behavior, but it's still strange that multiple tests produce the same results
- I've tested my hash generator just in case it was a problem on my side - everything was fine.
- Also it would be very nice if with suggestions for new additions to the table and ```hashrank``` the README file would also be updated with a table that includes new required collumns (less work for dqmis :) )

**Comment by Effanuel** [comment]
1. This function is not universal. It only supports **hex based hashes**. *(characters from '1' to 'f')*
2. Your hashing algorithm produces a hash that is not of base 16, so:
```C++
bits_per_hash = len(unihash(hash_name, get_word(rn_))) * 4
```
*Converting every character to binary is not going to produce correct results.
Conversion from hex to binary produces 4 bits.*

The length of your hash is **64** chars. But because it looks like it contains every characters in the alphabet, the actual bit representation is not **256-bits**. 

Example outputs:
* labas -> **Kr**9**G**450154134f3da127e10**h**E**Pi**e**g**ee4**JK**271ac617efce**n**51c4**d**89b243118491
* "./.......;]][]a22g" -> 17**m**08c1342**ip**ab**GG**19**ntm**0F4f**Ln**3e**J**e4**h**5**SKNTO**f**IiS**e2**O**3**WO6OXG**4**G**e422**cL**182
* 2 -> **Ni**bd3b317**d**4cf43b73**moKqn**7**l**1046e**kk**4941cf2732fc18bb39c3**nd**f**n**25**n**77F24

Highlighted are the characters that are not supposed to be there assuming your hash is hex based.

3. SequenceMatcher function doesn't compare bit differences.
>  The idea is to **find the longest contiguous matching subsequence that contains no “junk” elements**. The same idea is then applied recursively to the pieces of the sequences to the left and to the right of the matching subsequence. This does not yield minimal edit sequences, but does tend to yield matches that “look right” to people.

For example:
* `SequenceMatcher(None, "abc", "bcd").ratio() = 66.66%` *(it converts inputs to binary)*
* `RatioOfBits("abc" & "bcd") = 29.16%` because
011000010110001001100011 &
011000100110001101100100 =
011000000110001001100000
Number of matching bits is 7 out of 24 **(7/24*100 = 29.16%)**

SequenceMatcher function is useless if your hashing function is on average good.

4. I wanted this function to be as an alternative option, not mandatory.
> `#` was not removed from bit_collision call in main function - remove before testing.

**Comment by gitguuddd** [comment]
I am very thankful for the elaborate answers and examples, however next time it would be best if additional info would be added within the PR description for e.g hash compatibility (base 16 was not mandatory) or the intended use of the function as an alternative option - it would save time spent writing walls of text and running tests  :)

**Comment by Effanuel** [comment]
> I am very thankful for the elaborate answers and examples, however next time it would be best if additional info would be added within the PR description for e.g hash compatibility (base 16 was not mandatory) or the intended use of the function as an alternative option - it would save time spent writing walls of text and running tests :)

First time doing a pullback request:)

**Pull request closed without merging**
